// TasksTracker Website/src/app/pages/contact.component.ts
import { Component } from "@angular/core";
import { FormBuilder, FormGroup, Validators } from "@angular/forms";

@Component({
  selector: "app-contact",
  templateUrl: "./contact.component.html"
})
export class ContactComponent {
  contactForm: FormGroup;
  messageSent = false;

  constructor(private fb: FormBuilder) {
    this.contactForm = this.fb.group({
      name: ["", Validators.required],
      email: ["", [Validators.required, Validators.email]],
      message: ["", Validators.required]
    });
  }

  onSubmit(): void {
    if (this.contactForm.valid) {
      console.log("Form Data: ", this.contactForm.value); // replace with your actual submission code
      this.contactForm.reset();
      this.messageSent = true;
    }
  }
}

<div class="container py-5">
  <h1 class="text-center text-info">Contact Us</h1>

  <div class="card border-info bg-transparent my-4">
    <div class="card-body">
      <form [formGroup]="contactForm" (ngSubmit)="onSubmit()">
        <div class="mb-3">
          <label for="name" class="form-label text-warning">Your Name</label>
          <input
            type="text"
            formControlName="name"
            class="form-control bg-transparent text-info"
            id="name"
            required
          />
        </div>
        <div class="mb-3">
          <label for="email" class="form-label text-warning">Your Email</label>
          <input
            type="email"
            formControlName="email"
            class="form-control bg-transparent text-info"
            id="email"
            required
          />
        </div>
        <div class="mb-3">
          <label for="message" class="form-label text-warning"
            >Your Message</label
          >
          <textarea
            formControlName="message"
            class="form-control bg-transparent text-info"
            id="message"
            rows="3"
            required
          ></textarea>
        </div>
        <button
          type="submit"
          class="btn btn-info"
          [disabled]="!contactForm.valid"
        >
          Submit
        </button>
      </form>
      <h4 *ngIf="messageSent" class="text-center text-success mt-4">
        Your message has been sent!
      </h4>
    </div>
  </div>
</div>

// RecipeBoxWebsite/src/components/Contact.vue
<template>
  <div class="container my-5" style="color: #90A375">
    <h2 class="text-center">Contact Us</h2>
    <form @submit.prevent="handleSubmit">
      <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          v-model="name"
          required
        />
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          v-model="email"
          required
        />
      </div>
      <div class="mb-3">
        <label for="message" class="form-label">Message</label>
        <textarea
          class="form-control"
          id="message"
          rows="5"
          v-model="message"
          required
        ></textarea>
      </div>
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
  </div>
</template>
<script>
export default {
  name: "Contact",
  data() {
    return {
      name: "",
      email: "",
      message: "",
    };
  },
  methods: {
    handleSubmit() {
      alert("Your message has been sent!");
      window.location.reload();
    },
  },
};
</script>

<style scoped>
label {
  color: #F9BB9D;
}
</style>
